export const FETCHING_TIME='FETCHING_TIME';
export const FETCHING_FAILED='FETCHING_FAILED';

export const ERROR_ADDED='ERROR_ADDED';
export const ERROR_CLEARED='ERROR_CLEARED';

export const MESSAGE_ADDED='MESSAGE_ADDED';
export const MESSAGE_CLEARED='MESSAGE_CLEARED';

export const SIGN_UP_SUCCESS='SIGN_UP_SUCCESS';
export const SIGN_IN_ATTEMPING='SIGN_IN_ATTEMPING';
export const SIGN_IN_SUCCESS='SIGN_IN_SUCCESS';
export const LOG_OUT='LOG_OUT';
export const USER_GETTING ='USER_GETTING';
export const USER_UPDATED ='USER_UPDATED';


export const PRODUCT_ADDED='PRODUCT_ADDED';
export const PRODUCT_DELETED='PRODUCT_DELETED';
export const PRODUCT_ARCHIVED='PRODUCT_ARCHIVED';
export const PRODUCT_UPDATED='PRODUCT_UPDATED';
export const PRODUCTS_FETCHED='PRODUCTS_FETCHED';
export const PRODUCT_SEARCHED='PRODUCT_SEARCHED';
export const PRODUCT_FETCHED='PRODUCT_FETCHED';
export const PRODUCT_IMAGE_UPLOADED='PRODUCT_IMAGE_UPLOADED';


export const ORDER_ADDED='OREDER_ADDED';
export const ORDER_DELETED='OREDER_DELETED';
export const ORDER_UPDATED='OREDER_UPDATED';
export const ORDERS_FETCHED='OREDERS_FETCHED';
export const CARTS_FETCHED='CARTS_FETCHED';
export const CART_FETCHED='CART_FETCHED';
export const CHECHOUT='CHECKOUT';
export const STATUS_CHANGED='STATUS_CHANGED'

export const FAV_ORDER_ADDED='FAV_ORDER_ADDED';
export const FAV_ORDERS_FETCHED='FAV_ORDERS_FETCHED';



export const RATE_ADDED='RATE_ADDED';
export const RATES_FETCHED='RATES_FETCHED';




